services:
  db:
    image: postgres:17.2
    container_name: masters-db
    restart: always
    environment:
      POSTGRES_USER: masters
      POSTGRES_PASSWORD: default
      POSTGRES_DB: shipment_company
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    
  # api:
  #   image: masters-api
  #   container_name: masters-api
  #   restart: always
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - db
  #     - redis
  #   environment:
  #     DATABASE_URL: postgresql://masters:default@db:5432/shipment_company
  #     REDIS_URL: redis://redis:6379/0
      
volumes:
  db:
    driver: local
  redis:
    driver: local
    
